<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Barbershop.Data\Barbershop.Data.csproj" />
    <ProjectReference Include="..\Barbershop.Domain\Barbershop.Domain.csproj" />
    <ProjectReference Include="..\Barbershop.Shareable\Barbershop.Shareable.csproj" />
  </ItemGroup>

</Project>
