// <auto-generated />
using System;
using Barbershop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Barbershop.Data.Migrations
{
    [DbContext(typeof(BarbershopDbContext))]
    partial class BarbershopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Barbershop.Domain.Entity.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador único da entidade");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Data e hora de criação da entidade");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Descrição do serviço");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasComment("Duração do serviço");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasComment("Imagem do serviço");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indica se o serviço está ativo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Nome do serviço");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Preço do serviço");

                    b.Property<decimal?>("PromotionalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Preço promocional do serviço");

                    b.Property<DateTime?>("PromotionalPriceEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Data de término do preço promocional do serviço");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Data e hora da última atualização da entidade");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
